;             
CREATE USER IF NOT EXISTS "nttadmin" SALT '8a809c2cb7d626d2' HASH 'b3f31d3b7822e69df5b4e85d0af0c9d89cd9c6255e6200b050925d32f863332d' ADMIN;
CREATE MEMORY TABLE "PUBLIC"."PHONES"(
    "ID" VARCHAR(255) NOT NULL,
    "CITYCODE" VARCHAR(255),
    "COUNTRYCODE" VARCHAR(255),
    "NUMBER" VARCHAR(255),
    "USER_ID" VARCHAR(255) NOT NULL
);     
ALTER TABLE "PUBLIC"."PHONES" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_8" PRIMARY KEY("ID");       
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.PHONES;  
CREATE MEMORY TABLE "PUBLIC"."USERS"(
    "ID" VARCHAR(255) NOT NULL,
    "CREATED" TIMESTAMP,
    "MODIFIED" TIMESTAMP,
    "EMAIL" VARCHAR(255),
    "IS_ACTIVE" BOOLEAN,
    "LAST_LOGIN" TIMESTAMP,
    "NAME" VARCHAR(255),
    "PASSWORD" VARCHAR(255),
    "TOKEN" VARCHAR(255)
);      
ALTER TABLE "PUBLIC"."USERS" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");        
-- 0 +/- SELECT COUNT(*) FROM PUBLIC.USERS;   
ALTER TABLE "PUBLIC"."PHONES" ADD CONSTRAINT "PUBLIC"."FKMG6D77TGQFEN7N1G763NVSQE3" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USERS"("ID") ON DELETE CASCADE NOCHECK;       
